"""Generate kaggle/runner.py for M4 with the notebook and small shared files embedded.

    python models/M4_xgboost/kaggle/build_runner.py           # full run
    python models/M4_xgboost/kaggle/build_runner.py --smoke   # 3 settings, 60 rounds (pipeline check)

Large data comes from the private dataset `mitanshkanani/credit-risk-model-inputs`
(train + validation only, no test). XGBoost is not installed locally, so the smoke test
also runs on Kaggle.
"""

import base64
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parents[2]
SMOKE = "--smoke" in sys.argv

EMBED = {
    "models/M4_xgboost/M4_xgboost.ipynb": ROOT / "models" / "M4_xgboost" / "M4_xgboost.ipynb",
    "src/modeling/evaluation.py": ROOT / "src" / "modeling" / "evaluation.py",
    "models/leaderboard.csv": ROOT / "models" / "leaderboard.csv",
    "models/M3_lightgbm/results/m3_shap_importance.csv": ROOT / "models" / "M3_lightgbm" / "results" / "m3_shap_importance.csv",
}
FROM_DATASET = {
    "m1_B_validation_pd.parquet": "models/M1_logistic_regression/results/m1_B_validation_pd.parquet",
    "m3_validation_pd.parquet": "models/M3_lightgbm/results/m3_validation_pd.parquet",
}

embedded = {}
for rel, path in EMBED.items():
    data = path.read_bytes()
    if SMOKE and rel.endswith(".ipynb"):
        full = b"SEED, N_TRIALS, MAX_ROUNDS, EARLY_STOP, SEARCH_LR = 42, 40, 5000, 100, 0.05"
        assert full in data, "budget line not found in notebook"
        data = data.replace(full, b"SEED, N_TRIALS, MAX_ROUNDS, EARLY_STOP, SEARCH_LR = 42, 3, 60, 10, 0.05")
    embedded[rel] = base64.b64encode(data).decode("ascii")

runner = f'''"""Kaggle runner for M4 (generated by build_runner.py{" --smoke" if SMOKE else ""} - do not edit by hand).

Rebuilds the repo layout under /kaggle/working/repo from embedded files and the private
input dataset, then executes the M4 notebook with nbconvert so the executed notebook
(with every cell output) is saved as a kernel output file.
"""

import base64, os, shutil, subprocess, sys, time
from pathlib import Path

SMOKE = {SMOKE!r}
EMBEDDED = {embedded!r}
FROM_DATASET = {FROM_DATASET!r}

REPO = Path("/kaggle/working/repo")
INPUT = next(Path("/kaggle/input").rglob("X_train.parquet")).parent
print("Smoke run:", SMOKE, "| input dataset:", INPUT, sorted(p.name for p in INPUT.iterdir()))

for rel, data in EMBEDDED.items():
    path = REPO / rel
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_bytes(base64.b64decode(data))
for name, rel in FROM_DATASET.items():
    path = REPO / rel
    path.parent.mkdir(parents=True, exist_ok=True)
    shutil.copy(INPUT / name, path)
(REPO / "src" / "__init__.py").touch()
(REPO / "src" / "modeling" / "__init__.py").touch()

notebook = REPO / "models" / "M4_xgboost" / "M4_xgboost.ipynb"
print(f"CPU cores: {{os.cpu_count()}} | executing {{notebook}}", flush=True)
start = time.time()
subprocess.run([sys.executable, "-m", "jupyter", "nbconvert", "--to", "notebook", "--execute", "--inplace",
                "--ExecutePreprocessor.timeout=-1", "--ExecutePreprocessor.kernel_name=python3", str(notebook)],
               check=True)
print(f"Notebook executed in {{(time.time() - start) / 60:.1f}} minutes")
'''
(HERE / "runner.py").write_text(runner, encoding="utf-8")
print("wrote", HERE / "runner.py", "| smoke:", SMOKE, f"| {len(runner) / 1024:.0f} KB")
