"""Generate kaggle/runner.py for final Stage 2 (fairness + reason codes).

    python models/final/02_reason_codes_fairness/kaggle/build_runner.py

Stage 2 retrains three LightGBM models and computes SHAP values for 162,745 loans, which
needs more memory than the laptop has free, so it runs on a private Kaggle CPU kernel.
Data, the final M3 model file and Stage 1 predictions come from the private dataset
`mitanshkanani/credit-risk-model-inputs` (train + validation only, no test); small text
files are embedded here.
"""

import base64
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parents[3]
STAGE = "models/final/02_reason_codes_fairness"

EMBED = [
    f"{STAGE}/F2_reason_codes_fairness.ipynb",
    "src/modeling/evaluation.py",
    "src/modeling/reason_codes.py",
    "models/final/01_selection_calibration/results/final_model_choice.json",
    "models/final/01_selection_calibration/results/calibrator.json",
    "models/M3_lightgbm/results/m3_metrics.json",
]
FROM_DATASET = {
    "m3_B_mono.txt": "models/M3_lightgbm/results/m3_B_mono.txt",
    "f1_validation_pd.parquet": "models/final/01_selection_calibration/results/f1_validation_pd.parquet",
}
embedded = {rel: base64.b64encode((ROOT / rel).read_bytes()).decode("ascii") for rel in EMBED}

runner = f'''"""Kaggle runner for final Stage 2 (generated by build_runner.py - do not edit by hand)."""

import base64, os, shutil, subprocess, sys, time
from pathlib import Path

EMBEDDED = {embedded!r}
FROM_DATASET = {FROM_DATASET!r}

REPO = Path("/kaggle/working/repo")
INPUT = next(Path("/kaggle/input").rglob("X_train.parquet")).parent
print("Input dataset:", INPUT, sorted(p.name for p in INPUT.iterdir()))
for rel, data in EMBEDDED.items():
    path = REPO / rel
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_bytes(base64.b64decode(data))
for name, rel in FROM_DATASET.items():
    path = REPO / rel
    path.parent.mkdir(parents=True, exist_ok=True)
    shutil.copy(INPUT / name, path)
(REPO / "src" / "__init__.py").touch()
(REPO / "src" / "modeling" / "__init__.py").touch()

notebook = REPO / "{STAGE}" / "F2_reason_codes_fairness.ipynb"
print(f"CPU cores: {{os.cpu_count()}} | executing {{notebook}}", flush=True)
start = time.time()
subprocess.run([sys.executable, "-m", "jupyter", "nbconvert", "--to", "notebook", "--execute", "--inplace",
                "--ExecutePreprocessor.timeout=-1", "--ExecutePreprocessor.kernel_name=python3", str(notebook)],
               check=True)
print(f"Notebook executed in {{(time.time() - start) / 60:.1f}} minutes")
'''
(HERE / "runner.py").write_text(runner, encoding="utf-8")
print("wrote", HERE / "runner.py", f"({len(runner) / 1024:.0f} KB; embedded {len(EMBED)} files)")
