"""FastAPI service + web page for the credit-risk engine (Stage 6, live demo).

    uvicorn deploy.app.main:app --port 7860          (from the repo root)

GET  /                 web page (application form + result card)
GET  /api/health       engine loaded? model version
GET  /api/model        model card: test metrics, policy, inputs
GET  /api/samples      real validation applicants to start the form from
POST /api/score        one application (JSON) -> decision JSON
GET  /docs             interactive API documentation (generated by FastAPI)
"""

import json
import sys
from contextlib import asynccontextmanager
from pathlib import Path

from fastapi import FastAPI, HTTPException
from fastapi.responses import FileResponse
from fastapi.staticfiles import StaticFiles
from pydantic import BaseModel, ConfigDict, Field

APP_DIR = Path(__file__).resolve().parent
ROOT = APP_DIR.parents[1]
sys.path.insert(0, str(ROOT))

from src.engine import ApplicationError, CreditRiskEngine  # noqa: E402
from src.engine import guardrails as gr  # noqa: E402

STATE = {}


@asynccontextmanager
async def lifespan(app):
    STATE["engine"] = CreditRiskEngine()   # verifies bundle checksums + scikit-learn version
    STATE["samples"] = json.loads((APP_DIR / "samples.json").read_text(encoding="utf-8"))
    STATE["model_card"] = json.loads((APP_DIR / "model_card.json").read_text(encoding="utf-8"))
    yield


app = FastAPI(
    title="AI Credit Risk / Loan Approval Engine",
    description="LightGBM model (v1.0.0, frozen) trained on LendingClub accepted loans (2012-2014) with a v1.2 guardrail "
                "policy. Returns a calibrated probability of default, a risk band, a decision (APPROVE / REVIEW / DECLINE, or "
                "REFER when the applicant is outside the training data's range - then no score is given), the expected loss "
                "in USD and the main reasons. Educational demo - not a real lending decision.",
    version=gr.GUARDRAILS_VERSION,
    lifespan=lifespan,
)
app.mount("/static", StaticFiles(directory=APP_DIR / "static"), name="static")


class Application(BaseModel):
    """A loan application. Required: loan_amnt, term, annual_inc, dti, fico_range_low, earliest_cr_line ('Mar-2010'),
    home_ownership, verification_status, purpose, addr_state, revol_util, inq_last_6mths. Any of the engine's 65 input
    fields may be added (see /api/model); missing ones get typical training values and are listed in missing_fields."""

    model_config = ConfigDict(extra="allow", json_schema_extra={"example": {
        "loan_amnt": 12000, "term": 36, "purpose": "debt_consolidation", "annual_inc": 72000, "dti": 18.5,
        "fico_range_low": 700, "emp_length": "3 years", "home_ownership": "RENT", "verification_status": "Verified",
        "addr_state": "CA", "earliest_cr_line": "Mar-2010", "revol_util": 41.2, "revol_bal": 8500,
        "open_acc": 9, "total_acc": 20, "inq_last_6mths": 1}})

    loan_amnt: float = Field(..., gt=0, le=1_000_000, strict=True, allow_inf_nan=False, description="Loan amount in USD")
    term: int | str = Field(..., description="36 or 60 (months)")


@app.get("/", include_in_schema=False)
def index():
    return FileResponse(APP_DIR / "static" / "index.html")


@app.get("/api/health")
def health():
    engine = STATE.get("engine")
    return {"status": "ok" if engine else "loading",
            "model": engine.manifest["model_name"] if engine else None,
            "version": engine.manifest["version"] if engine else None,
            "policy_version": gr.GUARDRAILS_VERSION}


@app.get("/api/model")
def model_card():
    return STATE["model_card"]


@app.get("/api/samples")
def samples():
    return STATE["samples"]


@app.post("/api/score")
def score(application: Application):
    try:
        return STATE["engine"].score(application.model_dump())
    except ApplicationError as err:
        raise HTTPException(status_code=422, detail=str(err)) from None
