"""Generate kaggle/runner.py for M3 with the notebook, evaluation module and leaderboard embedded.

    python models/M3_lightgbm/kaggle/build_runner.py

Large data lives in the reusable private dataset `mitanshkanani/credit-risk-model-inputs`
(train + validation only, no test). Small, frequently changing files (notebook, shared
evaluation module, current leaderboard) are embedded in the runner so the dataset can be
reused by later models without re-uploading.
"""

import base64
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parents[2]

EMBED = {
    "models/M3_lightgbm/M3_lightgbm.ipynb": ROOT / "models" / "M3_lightgbm" / "M3_lightgbm.ipynb",
    "src/modeling/evaluation.py": ROOT / "src" / "modeling" / "evaluation.py",
    "models/leaderboard.csv": ROOT / "models" / "leaderboard.csv",
}
# files taken from the input dataset -> location in the rebuilt repo
FROM_DATASET = {
    "m1_B_validation_pd.parquet": "models/M1_logistic_regression/results/m1_B_validation_pd.parquet",
    "m2_validation_pd.parquet": "models/M2_random_forest/results/m2_validation_pd.parquet",
}

embedded = {k: base64.b64encode(v.read_bytes()).decode("ascii") for k, v in EMBED.items()}

runner = f'''"""Kaggle runner for M3 (generated by build_runner.py - do not edit by hand).

Rebuilds the repo layout under /kaggle/working/repo from embedded files and the
private input dataset, then executes the M3 notebook with nbconvert so the executed
notebook (with every cell output) is saved as a kernel output file.
"""

import base64, os, shutil, subprocess, sys, time
from pathlib import Path

EMBEDDED = {embedded!r}
FROM_DATASET = {FROM_DATASET!r}

REPO = Path("/kaggle/working/repo")
INPUT = next(Path("/kaggle/input").rglob("X_train.parquet")).parent
print("Input dataset:", INPUT, sorted(p.name for p in INPUT.iterdir()))

for rel, data in EMBEDDED.items():
    path = REPO / rel
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_bytes(base64.b64decode(data))
for name, rel in FROM_DATASET.items():
    path = REPO / rel
    path.parent.mkdir(parents=True, exist_ok=True)
    shutil.copy(INPUT / name, path)
(REPO / "src" / "__init__.py").touch()
(REPO / "src" / "modeling" / "__init__.py").touch()

notebook = REPO / "models" / "M3_lightgbm" / "M3_lightgbm.ipynb"
print(f"CPU cores: {{os.cpu_count()}} | executing {{notebook}}", flush=True)
start = time.time()
subprocess.run([sys.executable, "-m", "jupyter", "nbconvert", "--to", "notebook", "--execute", "--inplace",
                "--ExecutePreprocessor.timeout=-1", "--ExecutePreprocessor.kernel_name=python3", str(notebook)],
               check=True)
print(f"Notebook executed in {{(time.time() - start) / 60:.1f}} minutes")
'''
(HERE / "runner.py").write_text(runner, encoding="utf-8")
print("wrote", HERE / "runner.py", f"({len(runner) / 1024:.0f} KB, embedded: {list(EMBED)})")
